### ISSUE TITLE
Support csv tables in the table

### ISSUE THREAD

**Issue by LightGuard** [ahus1/anita-editor#342]
Showcase csv tables and the correct syntax

**Comment by ahus1** [comment]
Thanks for suggesting this. This is now available in all places: 

* The [Antora editor contains `tracks.csv`](https://github.com/ahus1/anita-editor/blob/main/public/tracks.csv).
* The[ Kata has been enhanced](https://github.com/ahus1/asciidoc-kata/blob/main/03_tables.adoc).
* The [AsciiDoc plugin for IntelliJ docs contain a section about CSV tables](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/technical-writing/using-tables-in-a-project.html).
